# Well-known courses worldwide: club, course, city, country, continent, par.
# Locations and pars only — no course rating or slope is invented here.
CURATED = [
# ---- Europe: British Isles
("Europe","Scotland","St Andrews","St Andrews Links","Old Course",72),
("Europe","Scotland","St Andrews","St Andrews Links","New Course",71),
("Europe","Scotland","St Andrews","St Andrews Links","Jubilee Course",72),
("Europe","Scotland","St Andrews","St Andrews Links","Castle Course",71),
("Europe","Scotland","Carnoustie","Carnoustie Golf Links","Championship",72),
("Europe","Scotland","Gullane","Muirfield","Championship",71),
("Europe","Scotland","Kingsbarns","Kingsbarns Golf Links","Championship",72),
("Europe","Scotland","Troon","Royal Troon Golf Club","Old Course",71),
("Europe","Scotland","Turnberry","Trump Turnberry","Ailsa",71),
("Europe","Scotland","Dornoch","Royal Dornoch Golf Club","Championship",70),
("Europe","Scotland","North Berwick","North Berwick Golf Club","West Links",71),
("Europe","Scotland","Auchterarder","Gleneagles","PGA Centenary",72),
("Europe","Scotland","Auchterarder","Gleneagles","King's Course",71),
("Europe","Scotland","Machrihanish","Machrihanish Dunes","Championship",72),
("Europe","England","Sunningdale","Sunningdale Golf Club","Old Course",70),
("Europe","England","Sunningdale","Sunningdale Golf Club","New Course",70),
("Europe","England","Virginia Water","Wentworth Club","West Course",72),
("Europe","England","Southport","Royal Birkdale Golf Club","Championship",70),
("Europe","England","Lytham St Annes","Royal Lytham & St Annes","Championship",70),
("Europe","England","Sandwich","Royal St George's Golf Club","Championship",70),
("Europe","England","Hoylake","Royal Liverpool Golf Club","Championship",72),
("Europe","England","Woking","Woburn Golf Club","Marquess",72),
("Europe","England","Newcastle upon Tyne","Close House","Colt",72),
("Europe","Northern Ireland","Newcastle","Royal County Down","Championship",71),
("Europe","Northern Ireland","Portrush","Royal Portrush Golf Club","Dunluce",72),
("Europe","Ireland","Doonbeg","Trump International Golf Links Doonbeg","Championship",72),
("Europe","Ireland","Ballybunion","Ballybunion Golf Club","Old Course",71),
("Europe","Ireland","Lahinch","Lahinch Golf Club","Old Course",72),
("Europe","Ireland","Portmarnock","Portmarnock Golf Club","Championship",72),
("Europe","Ireland","Straffan","The K Club","Palmer North",72),
("Europe","Wales","Newport","Celtic Manor Resort","Twenty Ten",71),
# ---- Europe: Iberia
("Europe","Spain","Sotogrande","Real Club Valderrama","Championship",71),
("Europe","Spain","Sotogrande","Real Club de Golf Sotogrande","Championship",72),
("Europe","Spain","Sotogrande","La Reserva Club","Championship",72),
("Europe","Spain","Casares","Finca Cortesin Golf Club","Championship",72),
("Europe","Spain","Marbella","Real Club de Golf Las Brisas","Championship",72),
("Europe","Spain","Benahavis","La Quinta Golf & Country Club","Championship",72),
("Europe","Spain","Madrid","Club de Campo Villa de Madrid","Negro",72),
("Europe","Spain","Girona","PGA Catalunya Resort","Stadium",72),
("Europe","Spain","Alicante","Las Colinas Golf & Country Club","Championship",71),
("Europe","Spain","Tenerife","Abama Golf","Championship",72),
("Europe","Portugal","Quinta do Lago","Quinta do Lago","South",72),
("Europe","Portugal","Quinta do Lago","Quinta do Lago","North",72),
("Europe","Portugal","Almancil","San Lorenzo Golf Course","Championship",72),
("Europe","Portugal","Vila Nova de Cacela","Monte Rei Golf & Country Club","North",72),
("Europe","Portugal","Vilamoura","Dom Pedro Victoria Golf Course","Championship",72),
("Europe","Portugal","Lisbon","Oitavos Dunes","Championship",71),
("Europe","Portugal","Comporta","Dunas Comporta","Championship",72),
# ---- Europe: Central & rest
("Europe","Austria","Atzenbrugg","Diamond Country Club","Championship",72),
("Europe","Austria","Fontana","Fontana Golf Club","Championship",72),
("Europe","Austria","Zell am See","Golfclub Zell am See-Kaprun","Schmittenhohe",72),
("Europe","Germany","Munich","Golfclub Munchen Eichenried","Championship",72),
("Europe","Germany","Cologne","Golf- und Land-Club Koln","Championship",72),
("Europe","Germany","Hamburg","Hamburger Golf-Club Falkenstein","Championship",71),
("Europe","Germany","Wittenbeck","Wittenbeck Golf Resort","Championship",72),
("Europe","Italy","Rome","Marco Simone Golf & Country Club","Championship",72),
("Europe","Italy","Turin","Royal Park I Roveri","Championship",72),
("Europe","Italy","Brescia","Franciacorta Golf Club","Championship",72),
("Europe","Italy","Sardinia","Is Molas Golf Club","Championship",72),
("Europe","France","Guyancourt","Le Golf National","Albatros",72),
("Europe","France","Chantilly","Golf de Chantilly","Vineuil",71),
("Europe","France","Biarritz","Golf de Biarritz Le Phare","Championship",69),
("Europe","France","Evian-les-Bains","Evian Resort Golf Club","Championship",71),
("Europe","Netherlands","Zandvoort","Kennemer Golf & Country Club","Championship",72),
("Europe","Netherlands","Cromvoirt","Bernardus Golf","Championship",72),
("Europe","Sweden","Halmstad","Halmstad Golfklubb","North",72),
("Europe","Denmark","Copenhagen","Royal Copenhagen Golf Club","Championship",72),
("Europe","Switzerland","Crans-Montana","Golf Club Crans-sur-Sierre","Severiano Ballesteros",70),
("Europe","Turkey","Belek","Regnum Carya Golf & Spa Resort","Championship",72),
("Europe","Turkey","Belek","Montgomerie Maxx Royal","Championship",72),
# ---- Middle East beyond the UAE
("Asia","Qatar","Doha","Doha Golf Club","Championship",72),
("Asia","Qatar","Doha","Education City Golf Club","Championship",72),
("Asia","Oman","Muscat","Al Mouj Golf","Championship",72),
("Asia","Oman","Muscat","Ghala Golf Club","Championship",71),
("Asia","Bahrain","Riffa","Royal Golf Club","Montgomerie",72),
("Asia","Saudi Arabia","King Abdullah Economic City","Royal Greens Golf & Country Club","Championship",72),
("Asia","Kuwait","Kuwait City","Sahara Golf Club","Championship",72),
("Asia","Jordan","Amman","Ayla Golf Club","Championship",72),
# ---- Asia
("Asia","Thailand","Bangkok","Alpine Golf Club","Championship",72),
("Asia","Thailand","Chonburi","Amata Spring Country Club","Championship",72),
("Asia","Thailand","Hua Hin","Black Mountain Golf Club","Championship",72),
("Asia","Thailand","Phuket","Blue Canyon Country Club","Canyon",72),
("Asia","Vietnam","Da Nang","Ba Na Hills Golf Club","Championship",72),
("Asia","Vietnam","Da Nang","Danang Golf Club","Dunes",72),
("Asia","Vietnam","Ho Chi Minh City","The Bluffs Ho Tram Strip","Championship",71),
("Asia","Singapore","Sentosa","Sentosa Golf Club","Serapong",72),
("Asia","Singapore","Sentosa","Sentosa Golf Club","New Tanjong",72),
("Asia","Malaysia","Kuala Lumpur","Kuala Lumpur Golf & Country Club","West",72),
("Asia","Indonesia","Jakarta","Pondok Indah Golf Course","Championship",72),
("Asia","India","Gurugram","DLF Golf & Country Club","Gary Player",72),
("Asia","India","Delhi","Delhi Golf Club","Lodhi",72),
("Asia","Japan","Chiba","Narashino Country Club","King",70),
("Asia","Japan","Hyogo","Hirono Golf Club","Championship",72),
("Asia","South Korea","Incheon","Jack Nicklaus Golf Club Korea","Championship",72),
("Asia","China","Shenzhen","Mission Hills Golf Club","World Cup",72),
("Asia","Philippines","Manila","Manila Southwoods Golf & Country Club","Masters",72),
# ---- Africa
("Africa","South Africa","George","Fancourt","The Links",73),
("Africa","South Africa","Malelane","Leopard Creek Country Club","Championship",72),
("Africa","South Africa","Sun City","Gary Player Country Club","Championship",72),
("Africa","South Africa","Cape Town","Steenberg Golf Club","Championship",72),
("Africa","South Africa","Durban","Durban Country Club","Championship",72),
("Africa","Morocco","Rabat","Royal Golf Dar Es Salam","Red",73),
("Africa","Morocco","Marrakech","Royal Golf Marrakech","Championship",72),
("Africa","Mauritius","Belle Mare","Constance Belle Mare Plage","Legend",72),
("Africa","Mauritius","Bel Ombre","Heritage Golf Club","Le Chateau",72),
("Africa","Egypt","Cairo","Katameya Heights Golf Resort","Championship",72),
("Africa","Kenya","Nairobi","Muthaiga Golf Club","Championship",71),
# ---- Oceania
("Oceania","Australia","Melbourne","Royal Melbourne Golf Club","West",72),
("Oceania","Australia","Melbourne","Kingston Heath Golf Club","Championship",72),
("Oceania","Australia","Sydney","New South Wales Golf Club","Championship",72),
("Oceania","Australia","Sydney","The Australian Golf Club","Championship",72),
("Oceania","Australia","Barnbougle","Barnbougle Dunes","Championship",71),
("Oceania","New Zealand","Te Awanga","Cape Kidnappers","Championship",71),
("Oceania","New Zealand","Matauri Bay","Kauri Cliffs","Championship",72),
("Oceania","New Zealand","Queenstown","Millbrook Resort","Coronet",72),
# ---- Americas beyond the US catalogue
("North America","Canada","Toronto","St. George's Golf and Country Club","Championship",71),
("North America","Canada","Ontario","Glen Abbey Golf Club","Championship",72),
("North America","Mexico","Los Cabos","Cabo del Sol","Ocean",72),
("North America","Mexico","Playa del Carmen","Mayakoba El Camaleon","Championship",72),
("North America","Dominican Republic","Punta Cana","Casa de Campo","Teeth of the Dog",72),
("South America","Argentina","Buenos Aires","Olivos Golf Club","Championship",72),
("South America","Brazil","Sao Paulo","Sao Paulo Golf Club","Championship",70),
]
