# -*- coding: utf-8 -*-
"""Every course on the Czech Golf Federation register (cgf.cz), with the
federation's own name, town and region. `rated` marks the courses the
federation lists as holding a USGA course/slope rating."""
# club, course, city, region, holes, par, rated
CZECHIA = [
 ("Albatross", "Championship", "Vysoký Újezd", "Středočeský kraj", 18, 72, True),
 ("Alfrédov", "Championship", "Kostelec u Stříbra", "Plzeňský kraj", 18, 72, True),
 ("Austerlitz", "Championship", "Slavkov u Brna", "Jihomoravský kraj", 18, 72, True),
 ("Barbora", "Championship", "Oldřichov u Duchcova", "Ústecký kraj", 18, 72, True),
 ("Benátky", "Championship", "Benátky nad Jizerou", "Středočeský kraj", 18, 72, True),
 ("Beroun", "Championship", "Beroun", "Středočeský kraj", 18, 72, True),
 ("Beřovice", "Championship", "Zlonice", "Středočeský kraj", 18, 72, True),
 ("Casa Serena", "Championship", "Kutná Hora", "Středočeský kraj", 18, 72, True),
 ("Cihelny", "Championship", "Bečov nad Teplou", "Karlovarský kraj", 18, 72, True),
 ("Černý Most - Black Bridge Resort", "Championship", "Praha 9 - Dolní Počernice", "Hlavní město Praha", 18, 72, True),
 ("Čertovo Břemeno", "Championship", "Jistebnice", "Jihočeský kraj", 18, 72, True),
 ("Česká Lípa", "Championship", "Nový Bor", "Liberecký kraj", 18, 72, True),
 ("Český Krumlov", "Championship", "Mirkovice", "Jihočeský kraj", 18, 72, True),
 ("Františkovy Lázně - Hazlov", "Championship", "Hazlov", "Karlovarský kraj", 18, 72, True),
 ("Golf Dobrouč", "Championship", "Dolní Dobrouč", "Pardubický kraj", 18, 72, True),
 ("Golf Resort Lázně Bohdaneč", "Championship", "Lázně Bohdaneč", "Pardubický kraj", 18, 72, True),
 ("Grabštejn", "Championship", "Chrastava", "Liberecký kraj", 18, 72, True),
 ("Greensgate Dýšina", "Championship", "Dýšina", "Plzeňský kraj", 18, 72, True),
 ("Hluboká", "Championship", "Hluboká nad Vltavou", "Jihočeský kraj", 18, 72, True),
 ("Hostivař", "Championship", "Praha 10", "Hlavní město Praha", 18, 72, True),
 ("Karlovy Vary", "Championship", "Karlovy Vary", "Karlovarský kraj", 18, 72, True),
 ("Kořenec", "Championship", "Boskovice", "Jihomoravský kraj", 18, 72, True),
 ("Kravaře", "Championship", "Kravaře", "Moravskoslezský kraj", 18, 72, True),
 ("Kunětická Hora", "Championship", "Dříteč", "Pardubický kraj", 18, 72, True),
 ("Liberec", "Championship", "Liberec - Machnín", "Liberecký kraj", 18, 72, True),
 ("Loreta Golf Pyšely", "Championship", "Pyšely", "Středočeský kraj", 18, 72, True),
 ("Malevil", "Championship", "Jablonné v Podještědí", "Liberecký kraj", 18, 72, True),
 ("Mariánské Lázně", "Championship", "Mariánské Lázně", "Karlovarský kraj", 18, 72, True),
 ("Mladá Boleslav", "Championship", "Mladá Boleslav", "Středočeský kraj", 18, 72, True),
 ("Mladé Buky", "Championship", "Mladé Buky", "Královéhradecký kraj", 18, 72, True),
 ("Mnich", "Championship", "Nová Bystřice", "Jihočeský kraj", 18, 72, True),
 ("Molitorov", "Championship", "Kouřim", "Středočeský kraj", 18, 72, True),
 ("Mstětice", "Championship", "Praha Východ", "Středočeský kraj", 18, 72, True),
 ("Olomouc", "Championship", "Dolany", "Olomoucký kraj", 18, 72, True),
 ("Ostravice", "Championship", "Ostravice", "Moravskoslezský kraj", 18, 72, True),
 ("PGA National - Prague Oaks", "Championship", "Popovičky", "Středočeský kraj", 18, 72, True),
 ("Písek - Kestřany", "Championship", "Kestřany", "Jihočeský kraj", 18, 72, True),
 ("Poděbrady", "Championship", "Poděbrady", "Středočeský kraj", 18, 72, True),
 ("Slapy", "Championship", "Slapy nad Vltavou", "Středočeský kraj", 18, 72, True),
 ("Sokolov", "Championship", "Dolní Rychnov", "Karlovarský kraj", 18, 72, True),
 ("Šilheřovice", "Championship", "Šilheřovice", "Moravskoslezský kraj", 18, 72, True),
 ("Telč", "Championship", "Telč", "Kraj Vysočina", 18, 72, True),
 ("Terasy Ústí nad Labem", "Championship", "Ústí nad Labem", "Ústecký kraj", 18, 72, True),
 ("Vinoř", "Championship", "Paha 9 - Vinoř", "Hlavní město Praha", 18, 72, True),
 ("Ypsilon Golf Liberec", "Championship", "Mníšek-Fojtka", "Liberecký kraj", 18, 72, True),
 ("Zbraslav - Prague City Golf", "Championship", "Praha-Lipence", "Hlavní město Praha", 18, 72, True),
 ("Bechyně", "Nine", "Bechyně", "Jihočeský kraj", 9, 36, True),
 ("Bitozeves", "Nine", "Louny", "Ústecký kraj", 9, 36, True),
 ("Botanika", "Nine", "Unhošť", "Středočeský kraj", 9, 36, True),
 ("Búřov", "Nine", "Valašská Bystřice", "Zlínský kraj", 9, 36, True),
 ("Cínovec", "Nine", "Dubí", "Ústecký kraj", 9, 36, True),
 ("Čapí hnízdo", "Nine", "Olbramovice", "Středočeský kraj", 9, 36, True),
 ("Grosshof", "Nine", "Broumov", "Královéhradecký kraj", 9, 36, True),
 ("Háje", "Nine", "Karlovy Vary", "Karlovarský kraj", 9, 36, True),
 ("Harrachov", "Nine", "Harrachov", "Liberecký kraj", 9, 36, True),
 ("Havlíčkův Brod", "Nine", "Havlíčkův Brod", "Kraj Vysočina", 9, 36, True),
 ("HEIPark", "Nine", "Odry", "Moravskoslezský kraj", 9, 36, True),
 ("Hodkovičky", "Nine", "Praha 4", "Hlavní město Praha", 9, 36, True),
 ("Holešov", "Nine", "Žopy u Holešova", "Zlínský kraj", 9, 36, True),
 ("Hořehledy", "Nine", "Spálené Poříčí", "Plzeňský kraj", 9, 36, True),
 ("Hradec Králové", "Nine", "Hradec Králové 2", "Královéhradecký kraj", 9, 36, True),
 ("Hukvaldy", "Nine", "Hukvaldy", "Moravskoslezský kraj", 9, 36, True),
 ("Janov", "Nine", "Janov", "Ústecký kraj", 9, 36, True),
 ("Ještěd", "Nine", "Český Dub", "Liberecký kraj", 9, 36, True),
 ("Jezera - Ostrožská Nová Ves", "Nine", "Ostrožská Nová Ves", "Zlínský kraj", 9, 36, True),
 ("Jihlava", "Nine", "Příseka", "Kraj Vysočina", 9, 36, True),
 ("Komárno pod Hostýnem", "Nine", "Komárno", "Zlínský kraj", 9, 36, True),
 ("Kotlina - Terezín", "Nine", "Terezín", "Ústecký kraj", 9, 36, True),
 ("Kšírovka", "Nine", "Brno", "Jihomoravský kraj", 9, 36, True),
 ("Lhotka", "Nine", "Lhotka", "Moravskoslezský kraj", 9, 36, False),
 ("Libouchec", "Nine", "Libouchec", "Ústecký kraj", 9, 36, True),
 ("Líšnice", "Nine", "Mníšek pod Brdy", "Středočeský kraj", 9, 36, True),
 ("Luby", "Nine", "Luby u Chebu", "Karlovarský kraj", 9, 36, True),
 ("Most", "Nine", "Most", "Ústecký kraj", 9, 36, True),
 ("Na Vrších", "Nine", "Třebechovice pod Orebem", "Královéhradecký kraj", 9, 36, True),
 ("Neurčeno", "Nine", "", "Středočeský kraj", 9, 36, False),
 ("Nová Bystřice", "Nine", "Nová Bystřice", "Jihočeský kraj", 9, 36, True),
 ("Osyčina", "Nine", "Vysoké Mýto", "Pardubický kraj", 9, 36, True),
 ("Podbořánky", "Nine", "Jesenice", "Středočeský kraj", 9, 36, True),
 ("Praha - Motol", "Nine", "Praha 5 - Motol", "Hlavní město Praha", 9, 36, True),
 ("Prosečné", "Nine", "Prosečné", "Královéhradecký kraj", 9, 36, True),
 ("Prštice", "Nine", "Prštice", "Jihomoravský kraj", 9, 36, False),
 ("Racing Karlovy Vary", "Nine", "Karlovy Vary", "Karlovarský kraj", 9, 36, True),
 ("Radíkov", "Nine", "Hranice", "Olomoucký kraj", 9, 36, True),
 ("Rothschild Golf Academy", "Nine", "Šilheřovice", "Moravskoslezský kraj", 9, 36, True),
 ("Rožnov pod Radhoštěm", "Nine", "Rožnov pod Radhoštěm", "Zlínský kraj", 9, 36, True),
 ("Semily", "Nine", "Semily", "Liberecký kraj", 9, 36, True),
 ("Slušovice", "Nine", "Slušovice", "Zlínský kraj", 9, 36, True),
 ("Stará Boleslav", "Nine", "Borek", "Středočeský kraj", 9, 36, True),
 ("Svobodné Hamry", "Nine", "Hlinsko v Čechách", "Pardubický kraj", 9, 36, True),
 ("Svratka", "Nine", "Svratka", "Kraj Vysočina", 9, 36, True),
 ("Těšetice", "Nine", "Prosiměřice", "Jihomoravský kraj", 9, 36, True),
 ("Úholičky - Snail Driving Range", "Nine", "Úholičky", "Středočeský kraj", 9, 36, True),
 ("Velké Karlovice - Horal", "Nine", "Velké Karlovice", "Zlínský kraj", 9, 36, True),
 ("Yard Resort - Předboj", "Nine", "Předboj", "Středočeský kraj", 9, 36, True),
 ("Zbraslav - Golf Park Praha", "Nine", "Praha - Zbraslav", "Hlavní město Praha", 9, 36, True),
 ("Zlín", "Nine", "Zlín 12 - Kostelec", "Zlínský kraj", 9, 36, True),
 ("Zlonín", "Nine", "Měšice u Prahy", "Středočeský kraj", 9, 36, False),
 ("Brno Kaskáda", "Championship", "Kuřim", "Jihomoravský kraj", 18, 72, True),
 ("Čeladná", "Championship", "Čeladná", "Moravskoslezský kraj", 18, 72, True),
 ("Darovanský dvůr", "Championship", "Břasy", "Plzeňský kraj", 18, 72, True),
 ("Karlštejn", "Championship", "Liteň", "Středočeský kraj", 18, 72, True),
 ("Konopiště", "Championship", "Benešov", "Středočeský kraj", 18, 72, True),
 ("Panorama Golf Resort - Kácov", "Championship", "Kácov", "Středočeský kraj", 18, 72, True),
 ("Ropice", "Championship", "Ropice", "Moravskoslezský kraj", 18, 72, True),
]
